### ISSUE TITLE
Shorthand conditionals check error

### ISSUE THREAD

**Issue by Anydog** [Ataurr/Theme-Mentor-For-Themeforest#2]
Hi,
perhaps you could tweak a bit your "sniffer" to skip shorthand conditionals. I suppose you're using `echo $         `, but when you have `echo $condition ? esc_attr( $my_dynamic_class ) : ''; `, this shouldn't report error.
And, we're using a lot of shorthand conditionals ... :)

**Comment by Ataurr** [comment]
We can do like this `echo esc_attr($bariable ) = $condition  ?  $my_dynamic_class: '';` ;)

_1. “late escaping” makes reviewers more efficient, which means customer code is reviewed and deployed faster,_

https://vip.wordpress.com/documentation/vip/best-practices/security/validating-sanitizing-escaping/#always-escape-late
